### ISSUE TITLE
Sugestão: Padronizar os editores de código egua.

### ISSUE THREAD

**Issue by gabrielloliveira** [eguatech/site#21]
Temos três editores. Os três se apresentam com interface diferentes para o usuário  (tudo bem. talvez o eguac precise de uma interface só para ele).

Acho que seria melhor ter somente uma rota ```/editor/``` onde poderia conter mais um select box para o estudante escolher entre os três módulos.

**Comment by gabrielloliveira** [comment]
Me desculpem se eu estiver criando a issue no lugar errado.

**Comment by lucaspompeun** [comment]
Opa, Gabriel. Em relação a isso há um motivo para a diferenciação das ferramentas. Temos um conjunto de soluções, gratuitas e de código aberto, para facilitar o acessa à programação para iniciantes e auxiliar no seu contínuo aprendizado, pra isso temos ferramentas que possuem nichos de uso, claro que todas com um objetivo em comum. O eguac e o eguap são módulos de programação que foram desenvolvidos para dar acessibilidade ao aprendizado das linguagens C e Python, respectivamente, o eguamat tem a função de ser um console matemático para aplicações que vão de análises simples até análises robustas de nível mestrado/doutorado, e a linguagem egua tem suas características próprias, sendo uma linguagem independente, que é executada tanto no ambiente web, com a IDEgua, quanto no ambiente local (ainda esta semana teremos no gerenciador de pacotes do npm, facilitando a instalação em ambientes Linux) sem ter necessariamente uma linguagem que levará para outras, já que estamos construindo-a constantemente para que ela se sustente, já a ferramenta eguafsm possui a característica de uma ferramenta para estudos teóricos de autômatos finitos, sendo a única ferramenta que de fato não tem foco para iniciantes em proramação.

**Comment by gabrielloliveira** [comment]
Entendi Lucas. Então, neste caso, acho que não exista mais necessidade dessa issue. Valeu pela resposta.
